include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    sort_constructors_first: true
    use_key_in_widget_constructors: true
    lines_longer_than_80_chars: false